// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoqcczgdrhjbxvwjoibr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvcWNjemdkcmhqYnh2d2pvaWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODYyNTgsImV4cCI6MjA1ODQ2MjI1OH0.S94UQubjsm8a6LHLtDXA90M8fNrAUIomm7CWDI5XvG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);